### ISSUE TITLE
use library in RecyclerView

### ISSUE THREAD

**Issue by imehrzadm** [Gavras/GIFView#1]
i want to use library in recyclerview but it has one problem : 
lib downloads gif every time on view create and need disk & memory cache. can you update library and add this feature?

**Comment by Gavras** [comment]
I thought about it when I did this library and I realized saving resources is not a view's job, and that's all what GIFView is. Maybe I am wrong. What would you do in my position? Maybe in a future release I will add a method call for Activities and sorts to tell the view to save its InputStream to a specified location for further use.
Just for clarification, you are talking about downloading gifs from the web right? Because if you store it in the phone it should load within a decent time and you can return to its original stopped time easily.

**Comment by dimensionv** [comment]
My two cents: When you get the GIF image via InputStream, you shouldn't care about caching, as the InputStream indicates the caller is actually taking care of these things already. However, as you offer downloading from the internet, that part should do the caching, as the user has no way to do that, when calling your GIFView.setGifResource(<uri>).

**Comment by Gavras** [comment]
Thank you for commenting, duly noted.

You're right and I really want to add a call to cache the InputStream when getting it from the internet.
As soon as I have time I'll do it, hopefully it will be soon.
Thanks again.

**Comment by dimensionv** [comment]
I have already a variant ready, let me test it a bit, and I will send you a pull request...if you don't mind.

**Comment by Gavras** [comment]
Of course I don't mind, thank you for putting an effort into this library.

Just notice that I tried in this library to let extending classes to instantiate the gif as they like (due to seeing many different libraries to showing gifs in many different ways).
I know the design I took is not flawless, but please try not to break that premise.

**Comment by dimensionv** [comment]
You have a pull request. I tried to hook into your process without too much interference, only caching when an URL was given to the view. I've tested it, and it works like charm, providing very fast access to the cached files, once they are downloaded :)

**Comment by Gavras** [comment]
@infinitydesign I know it has been a few months but maybe it's still relevant.
Does @dimensionv 's PR help you with your RecyclerView? @dimensionv added to the library a method to not download a gif every time and instead the library caches the gifs for further use.
